apiVersion: v1
kind: Service
metadata:
  name: firstapp
  labels:
    app: firstapp
spec:
  type: NodePort  
  selector:
    app: firstapp // pod
  ports:
    - name: http
      port: 8000
      targetPort: 8000
