apiVersion: v1
kind: Service
metadata:
  name: firstapp
  labels:
    app: firstapp
spec:
  type: NodePort
  selector:
    app: firstapp
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
