apiVersion: v2
name: firstapp
description: FirstAPP Helm chart
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: elasticsearch
    version: "22.1.6"
    repository: https://charts.bitnami.com/bitnami
  - name: kibana
    version: "11.0.0"
    repository: https://charts.bitnami.com/bitnami
