apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firstapp.fullname" . }}
  labels:
    {{- include "firstapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "firstapp.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "firstapp.labels" . | nindent 8 }}
    spec:
      containers:
        - name: firstapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_URL
              value: redis://redis:{{ .Values.redis.port }}/0
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 20
